import { readFile } from "node:fs/promises";
import { access } from "node:fs/promises";

const files = ["package.json", "electron/main.cjs", "electron/preload.cjs", "electron/update-contract.cjs", "src/App.tsx", "src/App.css", "public/shield.svg"];
for (const file of files) await access(new URL(`../${file}`, import.meta.url));
const main = await readFile(new URL("../electron/main.cjs", import.meta.url), "utf8");
const authClient = await readFile(new URL("../electron/auth-client.cjs", import.meta.url), "utf8");
const updateContract = await readFile(new URL("../electron/update-contract.cjs", import.meta.url), "utf8");
const app = await readFile(new URL("../src/App.tsx", import.meta.url), "utf8");
const packageJson = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
const required = ["/api/status", "/api/target", "/api/defender", "/api/thermostat/off", "authenticate", "boundedRequest", "projectConfig", "createLoginAttemptCoordinator", "completeLoginAttempt", "invalidateIfCurrent", "requestEffectIfCurrent", "validateApiResponse", "validateNotificationQuery", "validateNotificationAction", "validateTemperature", "validateEnabled", "boundedErrorDetail", "autoUpdater", "update-downloaded", "quitAndInstall", "normalizeUpdateFeedUrl", "probeSquirrelFeed", "manifestEntries"];
for (const marker of required) if (!main.includes(marker)) throw new Error(`Missing API/auth marker: ${marker}`);
for (const marker of ["_handler", "action", "__RequestVerificationToken", "CookieJar", "api/status", "selectLoginForm", "validateStatusSnapshot", "validateNotificationSnapshot", "persistCandidateSession", "HTTPS is required for non-loopback defender addresses", "Response body exceeds", "Request timed out", "Incorrect username or password"]) if (!authClient.includes(marker)) throw new Error(`Missing scoped auth marker: ${marker}`);
for (const marker of ["Ctrl+Shift+F", "bilingual", "funnyEnglish", "funnyCantonese", "SEARCH / REGEX BUILDER", "Guided regex blocks", "Raw pattern", "Sample text", "captures:", "Copy /pattern/flags", "Use in search", "Notification search regex builder", "Command palette regex builder", "settings-base-url", "settings-funny-en", "settings-update-feed", "settings-accent", "settings-font-family", "settings-font-scale", "appearance-preview", "focus the exact control", "role=\"tablist\"", "role=\"tabpanel\"", "aria-controls", "tabOrder", "tabAppearance", "Edit ", "Ctrl+Shift+←/→"]) if (!app.includes(marker)) throw new Error(`Missing controller feature: ${marker}`);
const warningMatch = updateContract.match(/const UNSIGNED_UPDATE_WARNING = "([^"]+)";/);
if (!warningMatch) throw new Error("Unsigned update warning constant is missing.");
for (const marker of ["Restart to install update", "updateFeedUrl", "UNSIGNED HTTPS UPDATE FEED", "Unsigned update feed", warningMatch[1]]) if (!app.includes(marker)) throw new Error(`Missing update/settings feature: ${marker}`);
for (const marker of ["UNSIGNED_UPDATE_WARNING", "unsignedWarning", "RELEASES/package-hash checks"]) if (!main.includes(marker)) throw new Error(`Missing unsigned update boundary: ${marker}`);
for (const stale of ["SIGNED UPDATE FEED", "Signed update feed", "signed RELEASES", "signature verification", "verified update"]) if (main.includes(stale) || app.includes(stale)) throw new Error(`Stale signed-update claim remains: ${stale}`);
if (packageJson.build?.win?.target?.[0]?.target !== "squirrel") throw new Error("Windows Squirrel packaging is required.");
if (main.includes("fake") || app.includes("fake HVAC")) throw new Error("Controller must not add fake HVAC state.");
if (/(?:10|192\\.168|172\\.(?:1[6-9]|2\\d|3[01]))\\./.test(main) || /(?:10|192\\.168|172\\.(?:1[6-9]|2\\d|3[01]))\\./.test(app)) throw new Error("Consumer source must not hard-code a private deployment address.");
if (main.indexOf("const candidate = await authenticate") > main.indexOf("completeLoginAttempt(")) throw new Error("Candidate session must be persisted before live connection assignment.");
if (!main.includes("maxBodyBytes: maxBodyBytes ?? 1024 * 1024")) throw new Error("Main API requests must have a bounded response body.");
if (!app.includes("setConfig((current) => ({ ...current, password: \"\" }))")) throw new Error("Renderer must clear the submitted password after a successful connect.");
if (authClient.includes("mergeCookies") || authClient.includes("onAuthenticated")) throw new Error("Authentication must use a URL-aware cookie jar and candidate session instead of legacy mutation.");
if (!packageJson.dependencies?.["tough-cookie"]) throw new Error("The production cookie-jar dependency is missing.");
const disconnectBlock = main.slice(main.indexOf("ipcMain.handle(\"auth:disconnect\""));
if (!disconnectBlock.includes("loginAttempts.begin();")) throw new Error("Disconnect must supersede pending login attempts.");
console.log("static-check: controller files, auth token path, API routes, language/tone controls, regex builder, and Squirrel target are present");
